language: java
sudo: required

install: /bin/true

jdk:
- oraclejdk8

env:
  global:
    - PGPORT=5432
    - PGHOST=localhost
    - DATABASE_URL=postgres://localhost:5432/HouseNow
services:
  - postgresql
addons:
  apt:
    sources:
    - precise-pgdg-9.5
    packages:
    - postgresql-9.5
    - postgresql-contrib-9.5
  postgresql: 9.5
  
  
before_install:
- gradle wrapper
- sudo apt-get install jq
- wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

before_script:
    - wget https://services.gradle.org/distributions/gradle-4.5-rc-1-bin.zip
    - unzip gradle-4.5-rc-1-bin.zip
    - export GRADLE_HOME=$PWD/gradle-4.5-rc-1
    - export PATH=$GRADLE_HOME/bin:$PATH
    - sudo cp /etc/postgresql/9.4/main/pg_hba.conf /etc/postgresql/9.5/main/pg_hba.conf
    - sudo /etc/init.d/postgresql restart
    - psql -U postgres -c 'CREATE DATABASE HouseNow;'
    - psql -c "CREATE USER test_user WITH PASSWORD 'kpi2015';" -U postgres 
    - psql -h localhost -p 5432 house_now


script:
- ./gradlew assemble
- ./gradlew check
- ./gradlew test --info
- ./gradlew codeCoverageReport
- ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
